# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - 3.1
  - 3.2
  - oldrel
  - release
  - devel

addons:
  apt:
    packages:
      - libboost-regex-dev

install:
- g++ -o credit_card_ex credit_card_example.cpp -lboost_regex

script:
- ./credit_card_ex
