environment:
  global:
    GCC_PATH: mingw_64
    BOOST_ROOT: C:\Libraries\boost_1_59_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib
    BOOST_INCLUDEDIR: C:\Libraries\boost_1_59_0\include\boost

install:
  - set PATH=C:\MinGW\bin;%PATH%
  - cd %BOOST_ROOT%
  - call bootstrap.bat mingw
  - .\b2 --toolset=gcc --with-regex
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - g++ credit_card_example.cpp -o credit_card_ex.exe -IC:\Libraries\boost_1_59_0 -LC:\Libraries\boost_1_59_0\stage\lib -lboost_regex-mgw53-mt-1_59

test_script:
  - credit_card_ex.exe
